class CompanyStorage {
  final String name;
  final List<String> prefixes;

  const CompanyStorage({required this.name, required this.prefixes});
}

const List<CompanyStorage> kCompanyStorages = [
  CompanyStorage(name: 'Excel Diamond Tools', prefixes: ['EDT']),
  CompanyStorage(name: 'Wheels India Limited', prefixes: ['WHEELS']),
  CompanyStorage(name: 'JK Fenner', prefixes: ['FEN', 'JK-FEN', 'JKFEN', 'JK']),
  CompanyStorage(name: 'Brakes India Limited Mahindra City', prefixes: ['BILS68', 'BILM68']),
  CompanyStorage(name: 'Brakes India Limited Solingar', prefixes: ['BILS']),
  CompanyStorage(name: 'Breaks India Limited', prefixes: ['BIL']),
  CompanyStorage(name: 'Rane Brake Lining Limited Trichy', prefixes: ['RBLT', 'RBL']),
  CompanyStorage(name: 'Rane Brakelining Limited Pondicherry', prefixes: ['RBLP', 'RBL']),
  CompanyStorage(name: 'Rane Brake Lining Limited Ambattur', prefixes: ['RBLA', 'RBL']),
  CompanyStorage(name: 'Rane Brakelining Limited Medak', prefixes: ['RBLM', 'RBL']),
  CompanyStorage(name: 'Unique Industries', prefixes: ['UNQ', 'UNI', 'UNIQ']),
  CompanyStorage(name: 'Pix Transmissions Limited', prefixes: ['PIX']),
  CompanyStorage(name: 'Krish Mettech', prefixes: ['KRISH']),
  CompanyStorage(name: 'Devi Polymers', prefixes: ['DEVI']),
  CompanyStorage(name: 'TPi Composites', prefixes: ['TPI']),
  CompanyStorage(name: 'Automotive Axles Limited', prefixes: ['AUTOAXLE']),
  CompanyStorage(name: 'JM Frictech', prefixes: ['JMI']),
  CompanyStorage(name: 'AS Industries', prefixes: ['ASIN']),
  CompanyStorage(name: 'Flowserve Sanmar Limited', prefixes: ['FLOW']),
  CompanyStorage(name: 'Federal Mogul', prefixes: ['FED']),
  CompanyStorage(name: 'Sangsin', prefixes: ['SANG']),
  CompanyStorage(name: 'Hitek Machines', prefixes: ['HI']),
  CompanyStorage(name: 'Yohasan', prefixes: ['YOHA']),
  CompanyStorage(name: 'Madras Metallurgical Services', prefixes: ['METSES']),
  CompanyStorage(name: 'Sundaram Brake Lining', prefixes: ['SBL']),
  CompanyStorage(name: 'Tools and Instruments Company', prefixes: ['TIC']),
  CompanyStorage(name: 'CPIN', prefixes: ['CPIN']),
  CompanyStorage(name: 'DPIN', prefixes: ['DPIN']),
  CompanyStorage(name: 'Lapping Compound', prefixes: ['LC']),
  CompanyStorage(name: 'SIC MARKING', prefixes: ['SIC']),
  CompanyStorage(name: 'RATEK Pheon', prefixes: ['RATEK']),
  CompanyStorage(name: 'AUTONEED', prefixes: ['AUTONEED']),
  CompanyStorage(name: 'KAIZEN Diamond Tools', prefixes: ['KAI']),
  CompanyStorage(name: 'Brakes india limited SRICITY', prefixes: []),
  CompanyStorage(name: 'BREMSKERL Friction', prefixes: ['BREM']),
  CompanyStorage(name: 'NORDEX', prefixes: ['NORDEX']),
  CompanyStorage(name: 'RAJ Mohini Industries', prefixes: ['RAJ']),
  CompanyStorage(name: 'KAYES Industries', prefixes: ['KAYES', 'KAY']),
  CompanyStorage(name: 'Accurate machines', prefixes: ['ACCU']),
  CompanyStorage(name: 'Bharat Rubber', prefixes: ['BHA']),
  CompanyStorage(name: 'ADMAC', prefixes: ['ADMAC', 'ADMACH']),
];
